### ISSUE TITLE
Add onboarding screen on startup of app

### ISSUE THREAD

**Issue by pratyaksh1610** [pratyaksh1610/Quiz_App#18]
Add onboarding screen 
Number of screens - 2

**Comment by lonewolf2208** [comment]
Hey @pratyaksh1610 can you assign this task this to me .

**Comment by pratyaksh1610** [comment]
@lonewolf2208 Screens must follow colour scheme and can show some features of the quiz ,just like any onboarding screen of an  app on startup shows.
