### ISSUE TITLE
Implement splash screen for the app following best practices

### ISSUE THREAD

**Issue by pratyaksh1610** [pratyaksh1610/Quiz_App#2]
Implement a splash screen for the application, 
EDIT -  Use the same icon as in the Login activity.

**Comment by Pritam0077** [comment]
Assign me

**Comment by sachin2709** [comment]
i want to work on this task ,Please Assign it to me @pratyaksh1610

**Comment by rishuyadav** [comment]
Hey @pratyaksh1610  am almost done with the splash screen, can you please assign it to me

**Comment by pratyaksh1610** [comment]
@rishuyadav Can you share a mockup of the change ?
