### ISSUE TITLE
Android app losing data during orientation change

### ISSUE THREAD

**Issue by lonewolf2208** [pratyaksh1610/Quiz_App#20]
Need to remove the landscape mode of the application as the data gets reloaded again .

https://user-images.githubusercontent.com/72886809/193653787-df3f6558-ca68-4b08-ac60-e335acd8d29b.mp4

**Comment by Fazil29** [comment]
I wanna work on it

**Comment by lonewolf2208** [comment]
Hey @Fazil29 if you are not working on it . I can solve this issue

**Comment by Fazil29** [comment]
hey @lonewolf2208 sorry man I solved this issue yesterday but forgot to push the code.
Maybe, you can work on structuring the project in to different packages, this is very much needed.

And a small request from my side, can you add hacktoberfest-accepted tag to the issue?
