### ISSUE TITLE
Add animation between activities

### ISSUE THREAD

**Issue by pratyaksh1610** [pratyaksh1610/Quiz_App#3]
Add animations between activities / fragments for smooth UI / UX, like `FADE`, 'END'.
Boost your creativity [🎉](https://emojipedia.org/party-popper/)

**Comment by Fazil29** [comment]
I wanna work on it

**Comment by pratyaksh1610** [comment]
@Fazil29 Assigned !
Happy coding [🎉](https://emojipedia.org/party-popper/)

**Comment by Fazil29** [comment]
could you please take a look at my PR?
