### ISSUE TITLE
Update the background colours of the options 

### ISSUE THREAD

**Issue by pratyaksh1610** [pratyaksh1610/Quiz_App#5]
Update the background colours of the options to avoid confusion after submitting a question.

## After clicking on submit
![qa](https://user-images.githubusercontent.com/76740999/193441130-4d0ecb14-0dd8-4adf-b13e-cf9996774df7.png)

**Comment by prayatharth** [comment]
@pratyaksh1610 could you please elaborate over the issue ?
like what type color change are you seeking ?

**Comment by pratyaksh1610** [comment]
@prayatharth After clicking on submit the correct option highlights to `green` and similarly the wrong highlights with `red`, so it becomes confusing for the user to differentiate between the selected and non selected options, so implement a colour scheme for the options for smooth accessibilty.

**Comment by pratyaksh1610** [comment]
If possible can implement like this, after clicking on submit only those views are visible which corresponds to right and wrong, and hide all  others without changing the color scheme.

**Comment by poseidon2060** [comment]
Can I work on this issue?

**Comment by ronakparmar533** [comment]
Hello @pratyaksh1610 , i am interested to work on this issue , can you please assign this to me ?
