### ISSUE TITLE
Redesign Progress bar 

### ISSUE THREAD

**Issue by pratyaksh1610** [pratyaksh1610/Quiz_App#6]
Open to suggestions
## Reference

https://user-images.githubusercontent.com/76740999/193441355-1ffeb0ba-3e3c-495a-83c5-95d94319c626.mp4

**Comment by lonewolf2208** [comment]
Hey @pratyaksh1610 i would like to work on this issue . Could you please assign this to me ?

**Comment by pratyaksh1610** [comment]
@lonewolf2208 Assigned this to you !
Happy Coding 👍
