### ISSUE TITLE
Remove unnecessary toast  and add a dialog instead 

### ISSUE THREAD

**Issue by criticalAY** [pratyaksh1610/Quiz_App#9]
Why are we having an unnecessary toast when selecting an option for the quiz? I don't think it's relevant as the user already know they are selecting.

**Comment by aneeshgupta25** [comment]
Kindly assign me this issue..I am working on it

**Comment by pratyaksh1610** [comment]
Part of issue : 
@aneeshgupta25 After removing the toast, please add a dialog showing some rules of the quiz with a non - cancellable 
'OK' button, and after pressing 'OK' it should move to the desired questions screen

**Comment by aneeshgupta25** [comment]
@pratyaksh1610 can you please suggest me which rules should I include in the dialog..?

**Comment by pratyaksh1610** [comment]
Rules to be included 

- The quiz will contains 10 random questions.
- Every correct answer scores you 1 point.
- Every wrong answer scores deducts 1 point.
- Results are visible at the end of the quiz.

**Comment by aneeshgupta25** [comment]
@pratyaksh1610 I have removed the Toast, added Dialog and have raised the PR. Kindly check the same.

**Comment by aneeshgupta25** [comment]
![Dialog](https://user-images.githubusercontent.com/77202061/193544155-0855f2c9-4a30-4763-a9fc-411d23b146b5.png)

Here's the screenshot for your reference.
